// Copyright (c) 2026 James Edwards
// SPDX-License-Identifier: MIT
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/**
 * @file Morpheme.h
 * @brief Zero-friction strong typedef wrapper.
 *
 * A @c Morpheme<Tag, T> is identical to @c T in every practical sense —
 * it constructs from @c T implicitly and converts back to @c T implicitly.
 * All operators are handled by the compiler via that implicit conversion,
 * so @c Morpheme works with any underlying type, numeric or otherwise.
 *
 * The sole purpose of the @c Tag parameter is to make otherwise identical
 * underlying types distinct to the compiler.  Two @c Morpheme types built
 * on the same @c T but different tags cannot be silently mixed, and the
 * disaggregation layer can dispatch to the correct handler for each, while
 * all other code treats them as plain @c T values.
 *
 * @note Arithmetic on two @c Morpheme values decays to @c T (via the implicit
 *       conversion), not back to @c Morpheme.  This is the correct trade-off
 *       when @c T may be non-numeric: the tag does its job at the dispatch
 *       boundary, and expressions behave exactly like plain @c T everywhere else.
 *
 * @par Defining a named type
 * @code
 *   // The tag struct can be forward-declared inline in the template argument.
 *   // No macro needed — this is one line of standard C++.
 *   using UUID   = DisAgg::Morpheme<struct UUIDTag,   int>;
 *   using TermID = DisAgg::Morpheme<struct TermIDTag, int>;
 *   using Label  = DisAgg::Morpheme<struct LabelTag,  std::string>;
 *
 *   UUID   a = 1;    // implicit from int
 *   TermID b = 2;    // implicit from int
 *   int    c = a;    // implicit to int
 * @endcode
 */

#pragma once
#include <utility>

namespace DisAgg {

/**
 * @brief Zero-friction strong typedef over an underlying type @c T.
 *
 * @tparam Tag  A unique type used solely as a type discriminator.  Typically
 *              the closure type of a @c decltype([]{}) expression, which is
 *              unique per source location in C++20 — no forward-declared tag
 *              struct required.  Two @c Morpheme instantiations with different
 *              @c Tag types are distinct types even when @c T is identical.
 * @tparam T    The underlying value type.  May be any copyable type.
 */
template<typename Tag, typename T>
struct Morpheme {

    /// The raw underlying value.  Accessible when an explicit extraction is needed.
    T value{};

    constexpr Morpheme() noexcept = default;

    /**
     * @brief Implicit construction from the underlying type.
     *
     * Allows existing code that produces @c T values to pass them to
     * functions or initialisers expecting a @c Morpheme with no changes.
     *
     * @param v  The raw value to wrap.
     */
    constexpr Morpheme(T v) noexcept : value(std::move(v)) {}

    /**
     * @brief Implicit conversion to a mutable lvalue reference.
     *
     * Allows a @c Morpheme to be passed directly to any function that takes
     * @c T& — including legacy APIs, output parameters, and @c scanf-style
     * interfaces — without an explicit @c .value access or cast.
     */
    constexpr operator T&()             noexcept { return value; }

    /**
     * @brief Implicit conversion to a const lvalue reference.
     *
     * Handles read-only contexts: @c const @c T& parameters, range-for over
     * a const container, and operators resolved via the underlying type.
     */
    constexpr operator const T&() const noexcept { return value; }
};

} // namespace DisAgg

/**
 * @brief Declares a named @c Morpheme type in one line.
 *
 * The tag struct is generated by the macro and never appears in user code.
 * From the caller's perspective it is simply:
 * @code
 *   MORPHEME(Temperature, float);   // one token — done
 * @endcode
 *
 * @par Why not decltype([]{})?
 * In C++20 each @c []{}  at a distinct source location is a unique closure
 * type, which makes it an appealing tag.  It works correctly on GCC and Clang,
 * which identify lambda types by source location across translation units.
 * MSVC however numbers lambdas per-TU, so the same @c []{}  in a shared
 * header gets a different mangled name in each @c .cpp file — a silent ODR
 * violation that causes linker errors.  The forward-declared tag struct is
 * used here because it is ODR-safe on all three compilers.
 *
 * @param Name  The desired type alias.
 * @param T     The underlying type.
 */
#define MORPHEME(Name, T) \
    using Name = DisAgg::Morpheme<struct Name##Tag, T>

/**
 * @brief Declares multiple @c Morpheme types that share the same underlying
 *        type, all in one line.
 *
 * Particularly useful when a domain has many semantically distinct quantities
 * that happen to share the same primitive (e.g. many @c float sensor readings,
 * or many @c long @c long timestamps and identifiers).
 *
 * @code
 *   // Five distinct float types — one line instead of five.
 *   MORPHEMES(float, Temperature, Pressure, Humidity, WindSpeed, Rainfall);
 *
 *   // Mix underlying types with separate calls:
 *   MORPHEMES(float,     StockPrice, MarketCap, DividendYield, PriceChange);
 *   MORPHEMES(long long, Volume, TradeId, Timestamp);
 * @endcode
 *
 * @note Macro-free C++20 alternative using unique lambda types as tags:
 * @code
 *   // Each decltype([]{}) at a distinct source location is a unique type.
 *   using Temperature = DisAgg::Morpheme<decltype([]{}), float>;
 *   using Pressure    = DisAgg::Morpheme<decltype([]{}), float>;
 * @endcode
 *
 * Supports up to 16 names per call (matching the struct field limit).
 *
 * @param T     The shared underlying type.
 * @param ...   One or more type names to declare.
 */
// MSVC's non-conforming preprocessor (default without /Zc:preprocessor) collapses
// a __VA_ARGS__ pack into a single token when it crosses a macro boundary.
// DISAGG_EXPAND forces one extra substitution pass, re-splitting the pack into
// individual arguments before the next macro receives them.
#define DISAGG_EXPAND(...) __VA_ARGS__

// Internal expanders — not part of the public API.
#define DISAGG_M1(T,a)      MORPHEME(a,T)
#define DISAGG_M2(T,a,...)  MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M1(T,__VA_ARGS__))
#define DISAGG_M3(T,a,...)  MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M2(T,__VA_ARGS__))
#define DISAGG_M4(T,a,...)  MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M3(T,__VA_ARGS__))
#define DISAGG_M5(T,a,...)  MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M4(T,__VA_ARGS__))
#define DISAGG_M6(T,a,...)  MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M5(T,__VA_ARGS__))
#define DISAGG_M7(T,a,...)  MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M6(T,__VA_ARGS__))
#define DISAGG_M8(T,a,...)  MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M7(T,__VA_ARGS__))
#define DISAGG_M9(T,a,...)  MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M8(T,__VA_ARGS__))
#define DISAGG_M10(T,a,...) MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M9(T,__VA_ARGS__))
#define DISAGG_M11(T,a,...) MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M10(T,__VA_ARGS__))
#define DISAGG_M12(T,a,...) MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M11(T,__VA_ARGS__))
#define DISAGG_M13(T,a,...) MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M12(T,__VA_ARGS__))
#define DISAGG_M14(T,a,...) MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M13(T,__VA_ARGS__))
#define DISAGG_M15(T,a,...) MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M14(T,__VA_ARGS__))
#define DISAGG_M16(T,a,...) MORPHEME(a,T); DISAGG_EXPAND(DISAGG_M15(T,__VA_ARGS__))

// Two-level CAT forces expansion of both args before the token paste.
#define DISAGG_CAT_I(a,b) a##b
#define DISAGG_CAT(a,b)   DISAGG_CAT_I(a,b)

// Parenthesised NARGS: passing the whole arg list as one macro argument and
// then "applying" NARGS to it forces MSVC to split it correctly.
#define DISAGG_NARGS(_1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,N,...) N
#define DISAGG_SEQ(args)  DISAGG_NARGS args
#define DISAGG_COUNT(...) DISAGG_SEQ((__VA_ARGS__,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1))

#define MORPHEMES(T,...) DISAGG_EXPAND(DISAGG_CAT(DISAGG_M, DISAGG_COUNT(__VA_ARGS__))(T,__VA_ARGS__))
